/*
 * arch/arm64/kernel/sys32.c
 *
 * Copyright (C) 2015 ARM Ltd.
 *
 * This program is free software(void); you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http(void);//www.gnu.org/licenses/>.
 */

/*
 * Needed to avoid conflicting __NR_* macros between uapi/asm/unistd.h and
 * asm/unistd32.h.
 */
#define __COMPAT_SYSCALL_NR

#include <linux/compiler.h>
#include <linux/syscalls.h>

asmlinkage long compat_sys_sigreturn_wrapper(void);
asmlinkage long compat_sys_rt_sigreturn_wrapper(void);
asmlinkage long compat_sys_statfs64_wrapper(void);
asmlinkage long compat_sys_fstatfs64_wrapper(void);
asmlinkage long compat_sys_pread64_wrapper(void);
asmlinkage long compat_sys_pwrite64_wrapper(void);
asmlinkage long compat_sys_truncate64_wrapper(void);
asmlinkage long compat_sys_ftruncate64_wrapper(void);
asmlinkage long compat_sys_readahead_wrapper(void);
asmlinkage long compat_sys_fadvise64_64_wrapper(void);
asmlinkage long compat_sys_sync_file_range2_wrapper(void);
asmlinkage long compat_sys_fallocate_wrapper(void);
asmlinkage long compat_sys_mmap2_wrapper(void);

#undef __SYSCALL
#define __SYSCALL(nr, sym)	[nr] = sym,

/*
 * The sys_call_table array must be 4K aligned to be accessible from
 * kernel/entry.S.
 */
/*
对compat_sys和正常的sys的调用不同之处如下：
1. 他们是通过不同的异常入口进来的，在arm64中如果发生了SVC异常，
对与系统在64位运行还是在32位运行进入各自的异常表，见entry.s的代码：
如果系统在64位运行则进入el0_sync->el0_svc异常表，从而调用sys_call_table中的函数，
如果系统在32位运行，则进入el0_sync_compat->el0_svc_compat异常表，从而调用compat_sys_call_table中的函数。
2. 对于同一个系统调用，64位和32位对应的系统调用号是不同的，例如ioctl在64位系统的调用号是29，而在32位的
则是54，这一点应该是通过不同的libc库保证的。
*/
void * const compat_sys_call_table[__NR_compat_syscalls] __aligned(4096) = {
#if 0
	[0 ... __NR_compat_syscalls - 1] = sys_ni_syscall,
#include <asm/unistd32.h>
#else
//预处理之后结果如下：
	[0 ... 390 - 1] = sys_ni_syscall,
	[0] = sys_restart_syscall,
	[1] = sys_exit,
	[2] = sys_fork,
	[3] = sys_read,
	[4] = sys_write,
	[5] = compat_sys_open,
	[6] = sys_close,
	[7] = sys_ni_syscall,
	[8] = sys_creat,
	[9] = sys_link,
	[10] = sys_unlink,
	[11] = compat_sys_execve,
	[12] = sys_chdir,
	[13] = sys_ni_syscall,
	[14] = sys_mknod,
	[15] = sys_chmod,
	[16] = sys_lchown16,
	[17] = sys_ni_syscall,
	[18] = sys_ni_syscall,
	[19] = compat_sys_lseek,
	[20] = sys_getpid,
	[21] = compat_sys_mount,
	[22] = sys_ni_syscall,
	[23] = sys_setuid16,
	[24] = sys_getuid16,
	[25] = sys_ni_syscall,
	[26] = compat_sys_ptrace,
	[27] = sys_ni_syscall,
	[28] = sys_ni_syscall,
	[29] = sys_pause,
	[30] = sys_ni_syscall,
	[31] = sys_ni_syscall,
	[32] = sys_ni_syscall,
	[33] = sys_access,
	[34] = sys_nice,
	[35] = sys_ni_syscall,
	[36] = sys_sync,
	[37] = sys_kill,
	[38] = sys_rename,
	[39] = sys_mkdir,
	[40] = sys_rmdir,
	[41] = sys_dup,
	[42] = sys_pipe,
	[43] = compat_sys_times,
	[44] = sys_ni_syscall,
	[45] = sys_brk,
	[46] = sys_setgid16,
	[47] = sys_getgid16,
	[48] = sys_ni_syscall,
	[49] = sys_geteuid16,
	[50] = sys_getegid16,
	[51] = sys_acct,
	[52] = sys_umount,
	[53] = sys_ni_syscall,
	[54] = compat_sys_ioctl,
	[55] = compat_sys_fcntl,
	[56] = sys_ni_syscall,
	[57] = sys_setpgid,
	[58] = sys_ni_syscall,
	[59] = sys_ni_syscall,
	[60] = sys_umask,
	[61] = sys_chroot,
	[62] = compat_sys_ustat,
	[63] = sys_dup2,
	[64] = sys_getppid,
	[65] = sys_getpgrp,
	[66] = sys_setsid,
	[67] = compat_sys_sigaction,
	[68] = sys_ni_syscall,
	[69] = sys_ni_syscall,
	[70] = sys_setreuid16,
	[71] = sys_setregid16,
	[72] = sys_sigsuspend,
	[73] = compat_sys_sigpending,
	[74] = sys_sethostname,
	[75] = compat_sys_setrlimit,
	[76] = sys_ni_syscall,
	[77] = compat_sys_getrusage,
	[78] = compat_sys_gettimeofday,
	[79] = compat_sys_settimeofday,
	[80] = sys_getgroups16,
	[81] = sys_setgroups16,
	[82] = sys_ni_syscall,
	[83] = sys_symlink,
	[84] = sys_ni_syscall,
	[85] = sys_readlink,
	[86] = sys_uselib,
	[87] = sys_swapon,
	[88] = sys_reboot,
	[89] = sys_ni_syscall,
	[90] = sys_ni_syscall,
	[91] = sys_munmap,
	[92] = compat_sys_truncate,
	[93] = compat_sys_ftruncate,
	[94] = sys_fchmod,
	[95] = sys_fchown16,
	[96] = sys_getpriority,
	[97] = sys_setpriority,
	[98] = sys_ni_syscall,
	[99] = compat_sys_statfs,
	[100] = compat_sys_fstatfs,
	[101] = sys_ni_syscall,
	[102] = sys_ni_syscall,
	[103] = sys_syslog,
	[104] = compat_sys_setitimer,
	[105] = compat_sys_getitimer,
	[106] = compat_sys_newstat,
	[107] = compat_sys_newlstat,
	[108] = compat_sys_newfstat,
	[109] = sys_ni_syscall,
	[110] = sys_ni_syscall,
	[111] = sys_vhangup,
	[112] = sys_ni_syscall,
	[113] = sys_ni_syscall,
	[114] = compat_sys_wait4,
	[115] = sys_swapoff,
	[116] = compat_sys_sysinfo,
	[117] = sys_ni_syscall,
	[118] = sys_fsync,
	[119] = compat_sys_sigreturn_wrapper,
	[120] = sys_clone,
	[121] = sys_setdomainname,
	[122] = sys_newuname,
	[123] = sys_ni_syscall,
	[124] = compat_sys_adjtimex,
	[125] = sys_mprotect,
	[126] = compat_sys_sigprocmask,
	[127] = sys_ni_syscall,
	[128] = sys_init_module,
	[129] = sys_delete_module,
	[130] = sys_ni_syscall,
	[131] = sys_quotactl,
	[132] = sys_getpgid,
	[133] = sys_fchdir,
	[134] = sys_bdflush,
	[135] = sys_sysfs,
	[136] = sys_personality,
	[137] = sys_ni_syscall,
	[138] = sys_setfsuid16,
	[139] = sys_setfsgid16,
	[140] = sys_llseek,
	[141] = compat_sys_getdents,
	[142] = compat_sys_select,
	[143] = sys_flock,
	[144] = sys_msync,
	[145] = compat_sys_readv,
	[146] = compat_sys_writev,
	[147] = sys_getsid,
	[148] = sys_fdatasync,
	[149] = compat_sys_sysctl,
	[150] = sys_mlock,
	[151] = sys_munlock,
	[152] = sys_mlockall,
	[153] = sys_munlockall,
	[154] = sys_sched_setparam,
	[155] = sys_sched_getparam,
	[156] = sys_sched_setscheduler,
	[157] = sys_sched_getscheduler,
	[158] = sys_sched_yield,
	[159] = sys_sched_get_priority_max,
	[160] = sys_sched_get_priority_min,
	[161] = compat_sys_sched_rr_get_interval,
	[162] = compat_sys_nanosleep,
	[163] = sys_mremap,
	[164] = sys_setresuid16,
	[165] = sys_getresuid16,
	[166] = sys_ni_syscall,
	[167] = sys_ni_syscall,
	[168] = sys_poll,
	[169] = sys_ni_syscall,
	[170] = sys_setresgid16,
	[171] = sys_getresgid16,
	[172] = sys_prctl,
	[173] = compat_sys_rt_sigreturn_wrapper,
	[174] = compat_sys_rt_sigaction,
	[175] = compat_sys_rt_sigprocmask,
	[176] = compat_sys_rt_sigpending,
	[177] = compat_sys_rt_sigtimedwait,
	[178] = compat_sys_rt_sigqueueinfo,
	[179] = compat_sys_rt_sigsuspend,
	[180] = compat_sys_pread64_wrapper,
	[181] = compat_sys_pwrite64_wrapper,
	[182] = sys_chown16,
	[183] = sys_getcwd,
	[184] = sys_capget,
	[185] = sys_capset,
	[186] = compat_sys_sigaltstack,
	[187] = compat_sys_sendfile,
	[188] = sys_ni_syscall,
	[189] = sys_ni_syscall,
	[190] = sys_vfork,
	[191] = compat_sys_getrlimit,
	[192] = compat_sys_mmap2_wrapper,
	[193] = compat_sys_truncate64_wrapper,
	[194] = compat_sys_ftruncate64_wrapper,
	[195] = sys_stat64,
	[196] = sys_lstat64,
	[197] = sys_fstat64,
	[198] = sys_lchown,
	[199] = sys_getuid,
	[200] = sys_getgid,
	[201] = sys_geteuid,
	[202] = sys_getegid,
	[203] = sys_setreuid,
	[204] = sys_setregid,
	[205] = sys_getgroups,
	[206] = sys_setgroups,
	[207] = sys_fchown,
	[208] = sys_setresuid,
	[209] = sys_getresuid,
	[210] = sys_setresgid,
	[211] = sys_getresgid,
	[212] = sys_chown,
	[213] = sys_setuid,
	[214] = sys_setgid,
	[215] = sys_setfsuid,
	[216] = sys_setfsgid,
	[217] = compat_sys_getdents64,
	[218] = sys_pivot_root,
	[219] = sys_mincore,
	[220] = sys_madvise,
	[221] = compat_sys_fcntl64,
	[222] = sys_ni_syscall,
	[223] = sys_ni_syscall,
	[224] = sys_gettid,
	[225] = compat_sys_readahead_wrapper,
	[226] = sys_setxattr,
	[227] = sys_lsetxattr,
	[228] = sys_fsetxattr,
	[229] = sys_getxattr,
	[230] = sys_lgetxattr,
	[231] = sys_fgetxattr,
	[232] = sys_listxattr,
	[233] = sys_llistxattr,
	[234] = sys_flistxattr,
	[235] = sys_removexattr,
	[236] = sys_lremovexattr,
	[237] = sys_fremovexattr,
	[238] = sys_tkill,
	[239] = sys_sendfile64,
	[240] = compat_sys_futex,
	[241] = compat_sys_sched_setaffinity,
	[242] = compat_sys_sched_getaffinity,
	[243] = compat_sys_io_setup,
	[244] = sys_io_destroy,
	[245] = compat_sys_io_getevents,
	[246] = compat_sys_io_submit,
	[247] = sys_io_cancel,
	[248] = sys_exit_group,
	[249] = compat_sys_lookup_dcookie,
	[250] = sys_epoll_create,
	[251] = sys_epoll_ctl,
	[252] = sys_epoll_wait,
	[253] = sys_remap_file_pages,
	[254] = sys_ni_syscall,
	[255] = sys_ni_syscall,
	[256] = sys_set_tid_address,
	[257] = compat_sys_timer_create,
	[258] = compat_sys_timer_settime,
	[259] = compat_sys_timer_gettime,
	[260] = sys_timer_getoverrun,
	[261] = sys_timer_delete,
	[262] = compat_sys_clock_settime,
	[263] = compat_sys_clock_gettime,
	[264] = compat_sys_clock_getres,
	[265] = compat_sys_clock_nanosleep,
	[266] = compat_sys_statfs64_wrapper,
	[267] = compat_sys_fstatfs64_wrapper,
	[268] = sys_tgkill,
	[269] = compat_sys_utimes,
	[270] = compat_sys_fadvise64_64_wrapper,
	[271] = sys_pciconfig_iobase,
	[272] = sys_pciconfig_read,
	[273] = sys_pciconfig_write,
	[274] = compat_sys_mq_open,
	[275] = sys_mq_unlink,
	[276] = compat_sys_mq_timedsend,
	[277] = compat_sys_mq_timedreceive,
	[278] = compat_sys_mq_notify,
	[279] = compat_sys_mq_getsetattr,
	[280] = compat_sys_waitid,
	[281] = sys_socket,
	[282] = sys_bind,
	[283] = sys_connect,
	[284] = sys_listen,
	[285] = sys_accept,
	[286] = sys_getsockname,
	[287] = sys_getpeername,
	[288] = sys_socketpair,
	[289] = sys_send,
	[290] = sys_sendto,
	[291] = compat_sys_recv,
	[292] = compat_sys_recvfrom,
	[293] = sys_shutdown,
	[294] = compat_sys_setsockopt,
	[295] = compat_sys_getsockopt,
	[296] = compat_sys_sendmsg,
	[297] = compat_sys_recvmsg,
	[298] = sys_semop,
	[299] = sys_semget,
	[300] = compat_sys_semctl,
	[301] = compat_sys_msgsnd,
	[302] = compat_sys_msgrcv,
	[303] = sys_msgget,
	[304] = compat_sys_msgctl,
	[305] = compat_sys_shmat,
	[306] = sys_shmdt,
	[307] = sys_shmget,
	[308] = compat_sys_shmctl,
	[309] = sys_add_key,
	[310] = sys_request_key,
	[311] = compat_sys_keyctl,
	[312] = compat_sys_semtimedop,
	[313] = sys_ni_syscall,
	[314] = sys_ioprio_set,
	[315] = sys_ioprio_get,
	[316] = sys_inotify_init,
	[317] = sys_inotify_add_watch,
	[318] = sys_inotify_rm_watch,
	[319] = compat_sys_mbind,
	[320] = compat_sys_get_mempolicy,
	[321] = compat_sys_set_mempolicy,
	[322] = compat_sys_openat,
	[323] = sys_mkdirat,
	[324] = sys_mknodat,
	[325] = sys_fchownat,
	[326] = compat_sys_futimesat,
	[327] = sys_fstatat64,
	[328] = sys_unlinkat,
	[329] = sys_renameat,
	[330] = sys_linkat,
	[331] = sys_symlinkat,
	[332] = sys_readlinkat,
	[333] = sys_fchmodat,
	[334] = sys_faccessat,
	[335] = compat_sys_pselect6,
	[336] = compat_sys_ppoll,
	[337] = sys_unshare,
	[338] = compat_sys_set_robust_list,
	[339] = compat_sys_get_robust_list,
	[340] = sys_splice,
	[341] = compat_sys_sync_file_range2_wrapper,
	[342] = sys_tee,
	[343] = compat_sys_vmsplice,
	[344] = compat_sys_move_pages,
	[345] = sys_getcpu,
	[346] = compat_sys_epoll_pwait,
	[347] = compat_sys_kexec_load,
	[348] = compat_sys_utimensat,
	[349] = compat_sys_signalfd,
	[350] = sys_timerfd_create,
	[351] = sys_eventfd,
	[352] = compat_sys_fallocate_wrapper,
	[353] = compat_sys_timerfd_settime,
	[354] = compat_sys_timerfd_gettime,
	[355] = compat_sys_signalfd4,
	[356] = sys_eventfd2,
	[357] = sys_epoll_create1,
	[358] = sys_dup3,
	[359] = sys_pipe2,
	[360] = sys_inotify_init1,
	[361] = compat_sys_preadv,
	[362] = compat_sys_pwritev,
	[363] = compat_sys_rt_tgsigqueueinfo,
	[364] = sys_perf_event_open,
	[365] = compat_sys_recvmmsg,
	[366] = sys_accept4,
	[367] = sys_fanotify_init,
	[368] = compat_sys_fanotify_mark,
	[369] = sys_prlimit64,
	[370] = sys_name_to_handle_at,
	[371] = compat_sys_open_by_handle_at,
	[372] = compat_sys_clock_adjtime,
	[373] = sys_syncfs,
	[374] = compat_sys_sendmmsg,
	[375] = sys_setns,
	[376] = compat_sys_process_vm_readv,
	[377] = compat_sys_process_vm_writev,
	[378] = sys_kcmp,
	[379] = sys_finit_module,
	[380] = sys_sched_setattr,
	[381] = sys_sched_getattr,
	[382] = sys_renameat2,
	[383] = sys_seccomp,
	[384] = sys_getrandom,
	[385] = sys_memfd_create,
	[386] = sys_bpf,
	[387] = compat_sys_execveat,
	[388] = sys_userfaultfd,
	[389] = sys_membarrier,

#endif
};
